/**-----------------------------------------------------------------------------
 * Copyright (c) 2025 Sergey Sanders
 * sergey@sesadesign.com
 * -----------------------------------------------------------------------------
 * Licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0
 * International (CC BY-NC-SA 4.0).
 *
 * You are free to:
 *  - Share: Copy and redistribute the material.
 *  - Adapt: Remix, transform, and build upon the material.
 *
 * Under the following terms:
 *  - Attribution: Give appropriate credit and indicate changes.
 *  - NonCommercial: Do not use for commercial purposes.
 *  - ShareAlike: Distribute under the same license.
 *
 * DISCLAIMER: This work is provided "as is" without any guarantees. The authors
 * aren’t responsible for any issues, damages, or claims that come up from using
 * it. Use at your own risk!
 *
 * Full license: http://creativecommons.org/licenses/by-nc-sa/4.0/
 * ---------------------------------------------------------------------------*/

/**
 %W = Word LSB MSB
 %B = Byte
 %R = Relative Address: +-127 bytes
 %A = Jump to an absolute address
*/
#include "stdint.h"
#include "z80mnx.h"
_opCodes_t opcode_basic[] =
    {    {.code = 0x00, .group = 0, .size = 1, .mnmx = "nop"},
         {.code = 0x01, .group = 0, .size = 3, .mnmx = "ld BC,%W"},
         {.code = 0x02, .group = 0, .size = 1, .mnmx = "ld (BC),A"},
         {.code = 0x03, .group = 0, .size = 1, .mnmx = "inc BC"},
         {.code = 0x04, .group = 0, .size = 1, .mnmx = "inc B"},
         {.code = 0x05, .group = 0, .size = 1, .mnmx = "dec B"},
         {.code = 0x06, .group = 0, .size = 2, .mnmx = "ld B,%B"},
         {.code = 0x07, .group = 0, .size = 1, .mnmx = "rlca"},
         {.code = 0x08, .group = 0, .size = 1, .mnmx = "ex AF,A'F'"},
         {.code = 0x09, .group = 0, .size = 1, .mnmx = "add HL,BC"},
         {.code = 0x0a, .group = 0, .size = 1, .mnmx = "ld A,(BC)"},
         {.code = 0x0b, .group = 0, .size = 1, .mnmx = "dec BC"},
         {.code = 0x0c, .group = 0, .size = 1, .mnmx = "inc C"},
         {.code = 0x0d, .group = 0, .size = 1, .mnmx = "dec C"},
         {.code = 0x0e, .group = 0, .size = 2, .mnmx = "ld C,%B"},
         {.code = 0x0f, .group = 0, .size = 1, .mnmx = "rrca"},
         {.code = 0x10, .group = 0, .size = 2, .mnmx = "djnz %R"},
         {.code = 0x11, .group = 0, .size = 3, .mnmx = "ld DE,%W"},
         {.code = 0x12, .group = 0, .size = 1, .mnmx = "ld (DE),A"},
         {.code = 0x13, .group = 0, .size = 1, .mnmx = "inc DE"},
         {.code = 0x14, .group = 0, .size = 1, .mnmx = "inc D"},
         {.code = 0x15, .group = 0, .size = 1, .mnmx = "dec D"},
         {.code = 0x16, .group = 0, .size = 2, .mnmx = "ld D,%B"},
         {.code = 0x17, .group = 0, .size = 1, .mnmx = "rla"},
         {.code = 0x18, .group = 0, .size = 2, .mnmx = "jr %R"},
         {.code = 0x19, .group = 0, .size = 1, .mnmx = "add HL,DE"},
         {.code = 0x1a, .group = 0, .size = 1, .mnmx = "ld A,(DE)"},
         {.code = 0x1b, .group = 0, .size = 1, .mnmx = "dec DE"},
         {.code = 0x1c, .group = 0, .size = 1, .mnmx = "inc E"},
         {.code = 0x1d, .group = 0, .size = 1, .mnmx = "dec E"},
         {.code = 0x1e, .group = 0, .size = 2, .mnmx = "ld E,%B"},
         {.code = 0x1f, .group = 0, .size = 1, .mnmx = "rra"},
         {.code = 0x20, .group = 0, .size = 2, .mnmx = "jr NZ,%R"},
         {.code = 0x21, .group = 0, .size = 3, .mnmx = "ld HL,%W"},
         {.code = 0x22, .group = 0, .size = 3, .mnmx = "ld (%W),HL"},
         {.code = 0x23, .group = 0, .size = 1, .mnmx = "inc HL"},
         {.code = 0x24, .group = 0, .size = 1, .mnmx = "inc H"},
         {.code = 0x25, .group = 0, .size = 1, .mnmx = "dec H"},
         {.code = 0x26, .group = 0, .size = 2, .mnmx = "ld H,%B"},
         {.code = 0x27, .group = 0, .size = 1, .mnmx = "daa"},
         {.code = 0x28, .group = 0, .size = 2, .mnmx = "jr Z,%R"},
         {.code = 0x29, .group = 0, .size = 1, .mnmx = "add HL,HL"},
         {.code = 0x2a, .group = 0, .size = 3, .mnmx = "ld HL,(%W)"},
         {.code = 0x2b, .group = 0, .size = 1, .mnmx = "dec HL"},
         {.code = 0x2c, .group = 0, .size = 1, .mnmx = "inc L"},
         {.code = 0x2d, .group = 0, .size = 1, .mnmx = "dec L"},
         {.code = 0x2e, .group = 0, .size = 2, .mnmx = "ld L,%B"},
         {.code = 0x2f, .group = 0, .size = 1, .mnmx = "cpl"},
         {.code = 0x30, .group = 0, .size = 2, .mnmx = "jr NC,%R"},
         {.code = 0x31, .group = 0, .size = 3, .mnmx = "ld SP,%W"},
         {.code = 0x32, .group = 0, .size = 3, .mnmx = "ld (%W),A"},
         {.code = 0x33, .group = 0, .size = 1, .mnmx = "inc SP"},
         {.code = 0x34, .group = 0, .size = 1, .mnmx = "inc (HL)"},
         {.code = 0x35, .group = 0, .size = 1, .mnmx = "dec (HL)"},
         {.code = 0x36, .group = 0, .size = 2, .mnmx = "ld (HL),%B"},
         {.code = 0x37, .group = 0, .size = 1, .mnmx = "scf"},
         {.code = 0x38, .group = 0, .size = 2, .mnmx = "jr C,%R"},
         {.code = 0x39, .group = 0, .size = 1, .mnmx = "add HL,SP"},
         {.code = 0x3a, .group = 0, .size = 3, .mnmx = "ld A,(%W)"},
         {.code = 0x3b, .group = 0, .size = 1, .mnmx = "dec SP"},
         {.code = 0x3c, .group = 0, .size = 1, .mnmx = "inc A"},
         {.code = 0x3d, .group = 0, .size = 1, .mnmx = "dec A"},
         {.code = 0x3e, .group = 0, .size = 2, .mnmx = "ld A,%B"},
         {.code = 0x3f, .group = 0, .size = 1, .mnmx = "ccf"},
         {.code = 0x40, .group = 0, .size = 1, .mnmx = "ld B,B"},
         {.code = 0x41, .group = 0, .size = 1, .mnmx = "ld B,C"},
         {.code = 0x42, .group = 0, .size = 1, .mnmx = "ld B,D"},
         {.code = 0x43, .group = 0, .size = 1, .mnmx = "ld B,E"},
         {.code = 0x44, .group = 0, .size = 1, .mnmx = "ld B,H"},
         {.code = 0x45, .group = 0, .size = 1, .mnmx = "ld B,L"},
         {.code = 0x46, .group = 0, .size = 1, .mnmx = "ld B,(HL)"},
         {.code = 0x47, .group = 0, .size = 1, .mnmx = "ld B,A"},
         {.code = 0x48, .group = 0, .size = 1, .mnmx = "ld C,B"},
         {.code = 0x49, .group = 0, .size = 1, .mnmx = "ld C,C"},
         {.code = 0x4a, .group = 0, .size = 1, .mnmx = "ld C,D"},
         {.code = 0x4b, .group = 0, .size = 1, .mnmx = "ld C,E"},
         {.code = 0x4c, .group = 0, .size = 1, .mnmx = "ld C,H"},
         {.code = 0x4d, .group = 0, .size = 1, .mnmx = "ld C,L"},
         {.code = 0x4e, .group = 0, .size = 1, .mnmx = "ld C,(HL)"},
         {.code = 0x4f, .group = 0, .size = 1, .mnmx = "ld C,A"},
         {.code = 0x50, .group = 0, .size = 1, .mnmx = "ld D,B"},
         {.code = 0x51, .group = 0, .size = 1, .mnmx = "ld D,C"},
         {.code = 0x52, .group = 0, .size = 1, .mnmx = "ld D,D"},
         {.code = 0x53, .group = 0, .size = 1, .mnmx = "ld D,E"},
         {.code = 0x54, .group = 0, .size = 1, .mnmx = "ld D,H"},
         {.code = 0x55, .group = 0, .size = 1, .mnmx = "ld D,L"},
         {.code = 0x56, .group = 0, .size = 1, .mnmx = "ld D,(HL)"},
         {.code = 0x57, .group = 0, .size = 1, .mnmx = "ld D,A"},
         {.code = 0x58, .group = 0, .size = 1, .mnmx = "ld E,B"},
         {.code = 0x59, .group = 0, .size = 1, .mnmx = "ld E,C"},
         {.code = 0x5a, .group = 0, .size = 1, .mnmx = "ld E,D"},
         {.code = 0x5b, .group = 0, .size = 1, .mnmx = "ld E,E"},
         {.code = 0x5c, .group = 0, .size = 1, .mnmx = "ld E,H"},
         {.code = 0x5d, .group = 0, .size = 1, .mnmx = "ld E,L"},
         {.code = 0x5e, .group = 0, .size = 1, .mnmx = "ld E,(HL)"},
         {.code = 0x5f, .group = 0, .size = 1, .mnmx = "ld E,A"},
         {.code = 0x60, .group = 0, .size = 1, .mnmx = "ld H,B"},
         {.code = 0x61, .group = 0, .size = 1, .mnmx = "ld H,C"},
         {.code = 0x62, .group = 0, .size = 1, .mnmx = "ld H,D"},
         {.code = 0x63, .group = 0, .size = 1, .mnmx = "ld H,E"},
         {.code = 0x64, .group = 0, .size = 1, .mnmx = "ld H,H"},
         {.code = 0x65, .group = 0, .size = 1, .mnmx = "ld H,L"},
         {.code = 0x66, .group = 0, .size = 1, .mnmx = "ld H,(HL)"},
         {.code = 0x67, .group = 0, .size = 1, .mnmx = "ld H,A"},
         {.code = 0x68, .group = 0, .size = 1, .mnmx = "ld L,B"},
         {.code = 0x69, .group = 0, .size = 1, .mnmx = "ld L,C"},
         {.code = 0x6a, .group = 0, .size = 1, .mnmx = "ld L,D"},
         {.code = 0x6b, .group = 0, .size = 1, .mnmx = "ld L,E"},
         {.code = 0x6c, .group = 0, .size = 1, .mnmx = "ld L,H"},
         {.code = 0x6d, .group = 0, .size = 1, .mnmx = "ld L,L"},
         {.code = 0x6e, .group = 0, .size = 1, .mnmx = "ld L,(HL)"},
         {.code = 0x6f, .group = 0, .size = 1, .mnmx = "ld L,A"},
         {.code = 0x70, .group = 0, .size = 1, .mnmx = "ld (HL),B"},
         {.code = 0x71, .group = 0, .size = 1, .mnmx = "ld (HL),C"},
         {.code = 0x72, .group = 0, .size = 1, .mnmx = "ld (HL),D"},
         {.code = 0x73, .group = 0, .size = 1, .mnmx = "ld (HL),E"},
         {.code = 0x74, .group = 0, .size = 1, .mnmx = "ld (HL),H"},
         {.code = 0x75, .group = 0, .size = 1, .mnmx = "ld (HL),L"},
         {.code = 0x76, .group = 0, .size = 1, .mnmx = "halt"},
         {.code = 0x77, .group = 0, .size = 1, .mnmx = "ld (HL),A"},
         {.code = 0x78, .group = 0, .size = 1, .mnmx = "ld A,B"},
         {.code = 0x79, .group = 0, .size = 1, .mnmx = "ld A,C"},
         {.code = 0x7a, .group = 0, .size = 1, .mnmx = "ld A,D"},
         {.code = 0x7b, .group = 0, .size = 1, .mnmx = "ld A,E"},
         {.code = 0x7c, .group = 0, .size = 1, .mnmx = "ld A,H"},
         {.code = 0x7d, .group = 0, .size = 1, .mnmx = "ld A,L"},
         {.code = 0x7e, .group = 0, .size = 1, .mnmx = "ld A,(HL)"},
         {.code = 0x7f, .group = 0, .size = 1, .mnmx = "ld A,A"},
         {.code = 0x80, .group = 0, .size = 1, .mnmx = "add A,B"},
         {.code = 0x81, .group = 0, .size = 1, .mnmx = "add A,C"},
         {.code = 0x82, .group = 0, .size = 1, .mnmx = "add A,D"},
         {.code = 0x83, .group = 0, .size = 1, .mnmx = "add A,E"},
         {.code = 0x84, .group = 0, .size = 1, .mnmx = "add A,H"},
         {.code = 0x85, .group = 0, .size = 1, .mnmx = "add A,L"},
         {.code = 0x86, .group = 0, .size = 1, .mnmx = "add A,(HL)"},
         {.code = 0x87, .group = 0, .size = 1, .mnmx = "add A,A"},
         {.code = 0x88, .group = 0, .size = 1, .mnmx = "adc A,B"},
         {.code = 0x89, .group = 0, .size = 1, .mnmx = "adc A,C"},
         {.code = 0x8a, .group = 0, .size = 1, .mnmx = "adc A,D"},
         {.code = 0x8b, .group = 0, .size = 1, .mnmx = "adc A,E"},
         {.code = 0x8c, .group = 0, .size = 1, .mnmx = "adc A,H"},
         {.code = 0x8d, .group = 0, .size = 1, .mnmx = "adc A,L"},
         {.code = 0x8e, .group = 0, .size = 1, .mnmx = "adc A,(HL)"},
         {.code = 0x8f, .group = 0, .size = 1, .mnmx = "adc A,A"},
         {.code = 0x90, .group = 0, .size = 1, .mnmx = "sub B"},
         {.code = 0x91, .group = 0, .size = 1, .mnmx = "sub C"},
         {.code = 0x92, .group = 0, .size = 1, .mnmx = "sub D"},
         {.code = 0x93, .group = 0, .size = 1, .mnmx = "sub E"},
         {.code = 0x94, .group = 0, .size = 1, .mnmx = "sub H"},
         {.code = 0x95, .group = 0, .size = 1, .mnmx = "sub L"},
         {.code = 0x96, .group = 0, .size = 1, .mnmx = "sub (HL)"},
         {.code = 0x97, .group = 0, .size = 1, .mnmx = "sub A"},
         {.code = 0x98, .group = 0, .size = 1, .mnmx = "sbc A,B"},
         {.code = 0x99, .group = 0, .size = 1, .mnmx = "sbc A,C"},
         {.code = 0x9a, .group = 0, .size = 1, .mnmx = "sbc A,D"},
         {.code = 0x9b, .group = 0, .size = 1, .mnmx = "sbc A,E"},
         {.code = 0x9c, .group = 0, .size = 1, .mnmx = "sbc A,H"},
         {.code = 0x9d, .group = 0, .size = 1, .mnmx = "sbc A,L"},
         {.code = 0x9e, .group = 0, .size = 1, .mnmx = "sbc A,(HL)"},
         {.code = 0x9f, .group = 0, .size = 1, .mnmx = "sbc A,A"},
         {.code = 0xa0, .group = 0, .size = 1, .mnmx = "and B"},
         {.code = 0xa1, .group = 0, .size = 1, .mnmx = "and C"},
         {.code = 0xa2, .group = 0, .size = 1, .mnmx = "and D"},
         {.code = 0xa3, .group = 0, .size = 1, .mnmx = "and E"},
         {.code = 0xa4, .group = 0, .size = 1, .mnmx = "and H"},
         {.code = 0xa5, .group = 0, .size = 1, .mnmx = "and L"},
         {.code = 0xa6, .group = 0, .size = 1, .mnmx = "and (HL)"},
         {.code = 0xa7, .group = 0, .size = 1, .mnmx = "and A"},
         {.code = 0xa8, .group = 0, .size = 1, .mnmx = "xor B"},
         {.code = 0xa9, .group = 0, .size = 1, .mnmx = "xor C"},
         {.code = 0xaa, .group = 0, .size = 1, .mnmx = "xor D"},
         {.code = 0xab, .group = 0, .size = 1, .mnmx = "xor E"},
         {.code = 0xac, .group = 0, .size = 1, .mnmx = "xor H"},
         {.code = 0xad, .group = 0, .size = 1, .mnmx = "xor L"},
         {.code = 0xae, .group = 0, .size = 1, .mnmx = "xor (HL)"},
         {.code = 0xaf, .group = 0, .size = 1, .mnmx = "xor A"},
         {.code = 0xb0, .group = 0, .size = 1, .mnmx = "or B"},
         {.code = 0xb1, .group = 0, .size = 1, .mnmx = "or C"},
         {.code = 0xb2, .group = 0, .size = 1, .mnmx = "or D"},
         {.code = 0xb3, .group = 0, .size = 1, .mnmx = "or E"},
         {.code = 0xb4, .group = 0, .size = 1, .mnmx = "or H"},
         {.code = 0xb5, .group = 0, .size = 1, .mnmx = "or L"},
         {.code = 0xb6, .group = 0, .size = 1, .mnmx = "or (HL)"},
         {.code = 0xb7, .group = 0, .size = 1, .mnmx = "or A"},
         {.code = 0xb8, .group = 0, .size = 1, .mnmx = "cp B"},
         {.code = 0xb9, .group = 0, .size = 1, .mnmx = "cp C"},
         {.code = 0xba, .group = 0, .size = 1, .mnmx = "cp D"},
         {.code = 0xbb, .group = 0, .size = 1, .mnmx = "cp E"},
         {.code = 0xbc, .group = 0, .size = 1, .mnmx = "cp H"},
         {.code = 0xbd, .group = 0, .size = 1, .mnmx = "cp L"},
         {.code = 0xbe, .group = 0, .size = 1, .mnmx = "cp (HL)"},
         {.code = 0xbf, .group = 0, .size = 1, .mnmx = "cp A"},
         {.code = 0xc0, .group = 0, .size = 1, .mnmx = "ret NZ"},
         {.code = 0xc1, .group = 0, .size = 1, .mnmx = "pop BC"},
         {.code = 0xc2, .group = 0, .size = 3, .mnmx = "jp NZ,%A"},
         {.code = 0xc3, .group = 0, .size = 3, .mnmx = "jp %A"},
         {.code = 0xc4, .group = 0, .size = 3, .mnmx = "call NZ,%A"},
         {.code = 0xc5, .group = 0, .size = 1, .mnmx = "push BC"},
         {.code = 0xc6, .group = 0, .size = 2, .mnmx = "add A,%B"},
         {.code = 0xc7, .group = 0, .size = 1, .mnmx = "rst 00H"},
         {.code = 0xc8, .group = 0, .size = 1, .mnmx = "ret Z"},
         {.code = 0xc9, .group = 0, .size = 1, .mnmx = "ret"},
         {.code = 0xca, .group = 0, .size = 3, .mnmx = "jp Z,%A"},
         {.code = 0xcb, .group = 1, .size = 0, .mnmx = "cb"},
         {.code = 0xcc, .group = 0, .size = 3, .mnmx = "call Z,%A"},
         {.code = 0xcd, .group = 0, .size = 3, .mnmx = "call %A"},
         {.code = 0xce, .group = 0, .size = 2, .mnmx = "adc A,%B"},
         {.code = 0xcf, .group = 0, .size = 1, .mnmx = "rst 08H"},
         {.code = 0xd0, .group = 0, .size = 1, .mnmx = "ret NC"},
         {.code = 0xd1, .group = 0, .size = 1, .mnmx = "pop DE"},
         {.code = 0xd2, .group = 0, .size = 3, .mnmx = "jp NC,%A"},
         {.code = 0xd3, .group = 0, .size = 2, .mnmx = "out (%B),A"},
         {.code = 0xd4, .group = 0, .size = 3, .mnmx = "call NC,%A"},
         {.code = 0xd5, .group = 0, .size = 1, .mnmx = "push DE"},
         {.code = 0xd6, .group = 0, .size = 2, .mnmx = "sub %B"},
         {.code = 0xd7, .group = 0, .size = 1, .mnmx = "rst 10H"},
         {.code = 0xd8, .group = 0, .size = 1, .mnmx = "ret C"},
         {.code = 0xd9, .group = 0, .size = 1, .mnmx = "exx"},
         {.code = 0xda, .group = 0, .size = 3, .mnmx = "jp C,%A"},
         {.code = 0xdb, .group = 0, .size = 2, .mnmx = "in A,(%B)"},
         {.code = 0xdc, .group = 0, .size = 3, .mnmx = "call C,%A"},
         {.code = 0xdd, .group = 2, .size = 0, .mnmx = "dd"},
         {.code = 0xde, .group = 0, .size = 2, .mnmx = "sbc A,%B"},
         {.code = 0xdf, .group = 0, .size = 1, .mnmx = "rst 18H"},
         {.code = 0xe0, .group = 0, .size = 1, .mnmx = "ret P0"},
         {.code = 0xe1, .group = 0, .size = 1, .mnmx = "pop HL"},
         {.code = 0xe2, .group = 0, .size = 3, .mnmx = "jp P0,%A"},
         {.code = 0xe3, .group = 0, .size = 1, .mnmx = "ex (SP),HL"},
         {.code = 0xe4, .group = 0, .size = 3, .mnmx = "call P0,%A"},
         {.code = 0xe5, .group = 0, .size = 1, .mnmx = "push HL"},
         {.code = 0xe6, .group = 0, .size = 2, .mnmx = "and %B"},
         {.code = 0xe7, .group = 0, .size = 1, .mnmx = "rst 20H"},
         {.code = 0xe8, .group = 0, .size = 1, .mnmx = "ret PE"},
         {.code = 0xe9, .group = 0, .size = 1, .mnmx = "jp (HL)"},
         {.code = 0xea, .group = 0, .size = 3, .mnmx = "jp PE,%A"},
         {.code = 0xeb, .group = 0, .size = 1, .mnmx = "ex DE,HL"},
         {.code = 0xec, .group = 0, .size = 3, .mnmx = "call PE,%A"},
         {.code = 0xed, .group = 4, .size = 0, .mnmx = "ed"},
         {.code = 0xee, .group = 0, .size = 2, .mnmx = "xor %B"},
         {.code = 0xef, .group = 0, .size = 1, .mnmx = "rst 28H"},
         {.code = 0xf0, .group = 0, .size = 1, .mnmx = "ret P"},
         {.code = 0xf1, .group = 0, .size = 1, .mnmx = "pop AF"},
         {.code = 0xf2, .group = 0, .size = 3, .mnmx = "jp P,%A"},
         {.code = 0xf3, .group = 0, .size = 1, .mnmx = "di"},
         {.code = 0xf4, .group = 0, .size = 3, .mnmx = "call P,%A"},
         {.code = 0xf5, .group = 0, .size = 1, .mnmx = "push AF"},
         {.code = 0xf6, .group = 0, .size = 2, .mnmx = "or %B"},
         {.code = 0xf7, .group = 0, .size = 1, .mnmx = "rst 30H"},
         {.code = 0xf8, .group = 0, .size = 1, .mnmx = "ret M"},
         {.code = 0xf9, .group = 0, .size = 1, .mnmx = "ld SP,HL"},
         {.code = 0xfa, .group = 0, .size = 3, .mnmx = "jp M,%A"},
         {.code = 0xfb, .group = 0, .size = 1, .mnmx = "ei"},
         {.code = 0xfc, .group = 0, .size = 3, .mnmx = "call M,%A"},
         {.code = 0xfd, .group = 5, .size = 0, .mnmx = "fd"},
         {.code = 0xfe, .group = 0, .size = 2, .mnmx = "cp %B"},
         {.code = 0xff, .group = 0, .size = 1, .mnmx = "rst 38H"},
     };
_opCodes_t opcode_CB[] =     
     {  
         {.code = 0x00, .group = 1, .size = 2, .mnmx = "rlc B"},
         {.code = 0x01, .group = 1, .size = 2, .mnmx = "rlc C"},
         {.code = 0x02, .group = 1, .size = 2, .mnmx = "rlc D"},
         {.code = 0x03, .group = 1, .size = 2, .mnmx = "rlc E"},
         {.code = 0x04, .group = 1, .size = 2, .mnmx = "rlc H"},
         {.code = 0x05, .group = 1, .size = 2, .mnmx = "rlc L"},
         {.code = 0x06, .group = 1, .size = 2, .mnmx = "rlc (HL)"},
         {.code = 0x07, .group = 1, .size = 2, .mnmx = "rlc A"},
         {.code = 0x08, .group = 1, .size = 2, .mnmx = "rrc B"},
         {.code = 0x09, .group = 1, .size = 2, .mnmx = "rrc C"},
         {.code = 0x0a, .group = 1, .size = 2, .mnmx = "rrc D"},
         {.code = 0x0b, .group = 1, .size = 2, .mnmx = "rrc E"},
         {.code = 0x0c, .group = 1, .size = 2, .mnmx = "rrc H"},
         {.code = 0x0d, .group = 1, .size = 2, .mnmx = "rrc L"},
         {.code = 0x0e, .group = 1, .size = 2, .mnmx = "rrc (HL)"},
         {.code = 0x0f, .group = 1, .size = 2, .mnmx = "rrc A"},
         {.code = 0x10, .group = 1, .size = 2, .mnmx = "rl B"},
         {.code = 0x11, .group = 1, .size = 2, .mnmx = "rl C"},
         {.code = 0x12, .group = 1, .size = 2, .mnmx = "rl D"},
         {.code = 0x13, .group = 1, .size = 2, .mnmx = "rl E"},
         {.code = 0x14, .group = 1, .size = 2, .mnmx = "rl H"},
         {.code = 0x15, .group = 1, .size = 2, .mnmx = "rl L"},
         {.code = 0x16, .group = 1, .size = 2, .mnmx = "rl (HL)"},
         {.code = 0x17, .group = 1, .size = 2, .mnmx = "rl A"},
         {.code = 0x18, .group = 1, .size = 2, .mnmx = "rr B"},
         {.code = 0x19, .group = 1, .size = 2, .mnmx = "rr C"},
         {.code = 0x1a, .group = 1, .size = 2, .mnmx = "rr D"},
         {.code = 0x1b, .group = 1, .size = 2, .mnmx = "rr E"},
         {.code = 0x1c, .group = 1, .size = 2, .mnmx = "rr H"},
         {.code = 0x1d, .group = 1, .size = 2, .mnmx = "rr L"},
         {.code = 0x1e, .group = 1, .size = 2, .mnmx = "rr (HL)"},
         {.code = 0x1f, .group = 1, .size = 2, .mnmx = "rr A"},
         {.code = 0x20, .group = 1, .size = 2, .mnmx = "sla B"},
         {.code = 0x21, .group = 1, .size = 2, .mnmx = "sla C"},
         {.code = 0x22, .group = 1, .size = 2, .mnmx = "sla D"},
         {.code = 0x23, .group = 1, .size = 2, .mnmx = "sla E"},
         {.code = 0x24, .group = 1, .size = 2, .mnmx = "sla H"},
         {.code = 0x25, .group = 1, .size = 2, .mnmx = "sla L"},
         {.code = 0x26, .group = 1, .size = 2, .mnmx = "sla (HL)"},
         {.code = 0x27, .group = 1, .size = 2, .mnmx = "sla A"},
         {.code = 0x28, .group = 1, .size = 2, .mnmx = "sra B"},
         {.code = 0x29, .group = 1, .size = 2, .mnmx = "sra C"},
         {.code = 0x2a, .group = 1, .size = 2, .mnmx = "sra D"},
         {.code = 0x2b, .group = 1, .size = 2, .mnmx = "sra E"},
         {.code = 0x2c, .group = 1, .size = 2, .mnmx = "sra H"},
         {.code = 0x2d, .group = 1, .size = 2, .mnmx = "sra L"},
         {.code = 0x2e, .group = 1, .size = 2, .mnmx = "sra (HL)"},
         {.code = 0x2f, .group = 1, .size = 2, .mnmx = "sra A"},
/*       {.code = 0x30, .group = 1, .size = 2, .mnmx = "sll B"},   // undocumented
         {.code = 0x31, .group = 1, .size = 2, .mnmx = "sll C"},   // undocumented
         {.code = 0x32, .group = 1, .size = 2, .mnmx = "sll D"},   // undocumented
         {.code = 0x33, .group = 1, .size = 2, .mnmx = "sll E"},   // undocumented
         {.code = 0x34, .group = 1, .size = 2, .mnmx = "sll H"},   // undocumented
         {.code = 0x35, .group = 1, .size = 2, .mnmx = "sll L"},   // undocumented
         {.code = 0x36, .group = 1, .size = 2, .mnmx = "sll (HL)"},// undocumented
         {.code = 0x37, .group = 1, .size = 2, .mnmx = "sll A"},   // undocumented    */  
         {.code = 0x38, .group = 1, .size = 2, .mnmx = "srl B"},
         {.code = 0x39, .group = 1, .size = 2, .mnmx = "srl C"},
         {.code = 0x3a, .group = 1, .size = 2, .mnmx = "srl D"},
         {.code = 0x3b, .group = 1, .size = 2, .mnmx = "srl E"},
         {.code = 0x3c, .group = 1, .size = 2, .mnmx = "srl H"},
         {.code = 0x3d, .group = 1, .size = 2, .mnmx = "srl L"},
         {.code = 0x3e, .group = 1, .size = 2, .mnmx = "srl (HL)"},
         {.code = 0x3f, .group = 1, .size = 2, .mnmx = "srl A"},
         {.code = 0x40, .group = 1, .size = 2, .mnmx = "bit 0,B"},
         {.code = 0x41, .group = 1, .size = 2, .mnmx = "bit 0,C"},
         {.code = 0x42, .group = 1, .size = 2, .mnmx = "bit 0,D"},
         {.code = 0x43, .group = 1, .size = 2, .mnmx = "bit 0,E"},
         {.code = 0x44, .group = 1, .size = 2, .mnmx = "bit 0,H"},
         {.code = 0x45, .group = 1, .size = 2, .mnmx = "bit 0,L"},
         {.code = 0x46, .group = 1, .size = 2, .mnmx = "bit 0,(HL)"},
         {.code = 0x47, .group = 1, .size = 2, .mnmx = "bit 0,A"},
         {.code = 0x48, .group = 1, .size = 2, .mnmx = "bit 1,B"},
         {.code = 0x49, .group = 1, .size = 2, .mnmx = "bit 1,C"},
         {.code = 0x4a, .group = 1, .size = 2, .mnmx = "bit 1,D"},
         {.code = 0x4b, .group = 1, .size = 2, .mnmx = "bit 1,E"},
         {.code = 0x4c, .group = 1, .size = 2, .mnmx = "bit 1,H"},
         {.code = 0x4d, .group = 1, .size = 2, .mnmx = "bit 1,L"},
         {.code = 0x4e, .group = 1, .size = 2, .mnmx = "bit 1,(HL)"},
         {.code = 0x4f, .group = 1, .size = 2, .mnmx = "bit 1,A"},
         {.code = 0x50, .group = 1, .size = 2, .mnmx = "bit 2,B"},
         {.code = 0x51, .group = 1, .size = 2, .mnmx = "bit 2,C"},
         {.code = 0x52, .group = 1, .size = 2, .mnmx = "bit 2,D"},
         {.code = 0x53, .group = 1, .size = 2, .mnmx = "bit 2,E"},
         {.code = 0x54, .group = 1, .size = 2, .mnmx = "bit 2,H"},
         {.code = 0x55, .group = 1, .size = 2, .mnmx = "bit 2,L"},
         {.code = 0x56, .group = 1, .size = 2, .mnmx = "bit 2,(HL)"},
         {.code = 0x57, .group = 1, .size = 2, .mnmx = "bit 2,A"},
         {.code = 0x58, .group = 1, .size = 2, .mnmx = "bit 3,B"},
         {.code = 0x59, .group = 1, .size = 2, .mnmx = "bit 3,C"},
         {.code = 0x5a, .group = 1, .size = 2, .mnmx = "bit 3,D"},
         {.code = 0x5b, .group = 1, .size = 2, .mnmx = "bit 3,E"},
         {.code = 0x5c, .group = 1, .size = 2, .mnmx = "bit 3,H"},
         {.code = 0x5d, .group = 1, .size = 2, .mnmx = "bit 3,L"},
         {.code = 0x5e, .group = 1, .size = 2, .mnmx = "bit 3,(HL)"},
         {.code = 0x5f, .group = 1, .size = 2, .mnmx = "bit 3,A"},
         {.code = 0x60, .group = 1, .size = 2, .mnmx = "bit 4,B"},
         {.code = 0x61, .group = 1, .size = 2, .mnmx = "bit 4,C"},
         {.code = 0x62, .group = 1, .size = 2, .mnmx = "bit 4,D"},
         {.code = 0x63, .group = 1, .size = 2, .mnmx = "bit 4,E"},
         {.code = 0x64, .group = 1, .size = 2, .mnmx = "bit 4,H"},
         {.code = 0x65, .group = 1, .size = 2, .mnmx = "bit 4,L"},
         {.code = 0x66, .group = 1, .size = 2, .mnmx = "bit 4,(HL)"},
         {.code = 0x67, .group = 1, .size = 2, .mnmx = "bit 4,A"},
         {.code = 0x68, .group = 1, .size = 2, .mnmx = "bit 5,B"},
         {.code = 0x69, .group = 1, .size = 2, .mnmx = "bit 5,C"},
         {.code = 0x6a, .group = 1, .size = 2, .mnmx = "bit 5,D"},
         {.code = 0x6b, .group = 1, .size = 2, .mnmx = "bit 5,E"},
         {.code = 0x6c, .group = 1, .size = 2, .mnmx = "bit 5,H"},
         {.code = 0x6d, .group = 1, .size = 2, .mnmx = "bit 5,L"},
         {.code = 0x6e, .group = 1, .size = 2, .mnmx = "bit 5,(HL)"},
         {.code = 0x6f, .group = 1, .size = 2, .mnmx = "bit 5,A"},
         {.code = 0x70, .group = 1, .size = 2, .mnmx = "bit 6,B"},
         {.code = 0x71, .group = 1, .size = 2, .mnmx = "bit 6,C"},
         {.code = 0x72, .group = 1, .size = 2, .mnmx = "bit 6,D"},
         {.code = 0x73, .group = 1, .size = 2, .mnmx = "bit 6,E"},
         {.code = 0x74, .group = 1, .size = 2, .mnmx = "bit 6,H"},
         {.code = 0x75, .group = 1, .size = 2, .mnmx = "bit 6,L"},
         {.code = 0x76, .group = 1, .size = 2, .mnmx = "bit 6,(HL)"},
         {.code = 0x77, .group = 1, .size = 2, .mnmx = "bit 6,A"},
         {.code = 0x78, .group = 1, .size = 2, .mnmx = "bit 7,B"},
         {.code = 0x79, .group = 1, .size = 2, .mnmx = "bit 7,C"},
         {.code = 0x7a, .group = 1, .size = 2, .mnmx = "bit 7,D"},
         {.code = 0x7b, .group = 1, .size = 2, .mnmx = "bit 7,E"},
         {.code = 0x7c, .group = 1, .size = 2, .mnmx = "bit 7,H"},
         {.code = 0x7d, .group = 1, .size = 2, .mnmx = "bit 7,L"},
         {.code = 0x7e, .group = 1, .size = 2, .mnmx = "bit 7,(HL)"},
         {.code = 0x7f, .group = 1, .size = 2, .mnmx = "bit 7,A"},
         {.code = 0x80, .group = 1, .size = 2, .mnmx = "res 0,B"},
         {.code = 0x81, .group = 1, .size = 2, .mnmx = "res 0,C"},
         {.code = 0x82, .group = 1, .size = 2, .mnmx = "res 0,D"},
         {.code = 0x83, .group = 1, .size = 2, .mnmx = "res 0,E"},
         {.code = 0x84, .group = 1, .size = 2, .mnmx = "res 0,H"},
         {.code = 0x85, .group = 1, .size = 2, .mnmx = "res 0,L"},
         {.code = 0x86, .group = 1, .size = 2, .mnmx = "res 0,(HL)"},
         {.code = 0x87, .group = 1, .size = 2, .mnmx = "res 0,A"},
         {.code = 0x88, .group = 1, .size = 2, .mnmx = "res 1,B"},
         {.code = 0x89, .group = 1, .size = 2, .mnmx = "res 1,C"},
         {.code = 0x8a, .group = 1, .size = 2, .mnmx = "res 1,D"},
         {.code = 0x8b, .group = 1, .size = 2, .mnmx = "res 1,E"},
         {.code = 0x8c, .group = 1, .size = 2, .mnmx = "res 1,H"},
         {.code = 0x8d, .group = 1, .size = 2, .mnmx = "res 1,L"},
         {.code = 0x8e, .group = 1, .size = 2, .mnmx = "res 1,(HL)"},
         {.code = 0x8f, .group = 1, .size = 2, .mnmx = "res 1,A"},
         {.code = 0x90, .group = 1, .size = 2, .mnmx = "res 2,B"},
         {.code = 0x91, .group = 1, .size = 2, .mnmx = "res 2,C"},
         {.code = 0x92, .group = 1, .size = 2, .mnmx = "res 2,D"},
         {.code = 0x93, .group = 1, .size = 2, .mnmx = "res 2,E"},
         {.code = 0x94, .group = 1, .size = 2, .mnmx = "res 2,H"},
         {.code = 0x95, .group = 1, .size = 2, .mnmx = "res 2,L"},
         {.code = 0x96, .group = 1, .size = 2, .mnmx = "res 2,(HL)"},
         {.code = 0x97, .group = 1, .size = 2, .mnmx = "res 2,A"},
         {.code = 0x98, .group = 1, .size = 2, .mnmx = "res 3,B"},
         {.code = 0x99, .group = 1, .size = 2, .mnmx = "res 3,C"},
         {.code = 0x9a, .group = 1, .size = 2, .mnmx = "res 3,D"},
         {.code = 0x9b, .group = 1, .size = 2, .mnmx = "res 3,E"},
         {.code = 0x9c, .group = 1, .size = 2, .mnmx = "res 3,H"},
         {.code = 0x9d, .group = 1, .size = 2, .mnmx = "res 3,L"},
         {.code = 0x9e, .group = 1, .size = 2, .mnmx = "res 3,(HL)"},
         {.code = 0x9f, .group = 1, .size = 2, .mnmx = "res 3,A"},
         {.code = 0xa0, .group = 1, .size = 2, .mnmx = "res 4,B"},
         {.code = 0xa1, .group = 1, .size = 2, .mnmx = "res 4,C"},
         {.code = 0xa2, .group = 1, .size = 2, .mnmx = "res 4,D"},
         {.code = 0xa3, .group = 1, .size = 2, .mnmx = "res 4,E"},
         {.code = 0xa4, .group = 1, .size = 2, .mnmx = "res 4,H"},
         {.code = 0xa5, .group = 1, .size = 2, .mnmx = "res 4,L"},
         {.code = 0xa6, .group = 1, .size = 2, .mnmx = "res 4,(HL)"},
         {.code = 0xa7, .group = 1, .size = 2, .mnmx = "res 4,A"},
         {.code = 0xa8, .group = 1, .size = 2, .mnmx = "res 5,B"},
         {.code = 0xa9, .group = 1, .size = 2, .mnmx = "res 5,C"},
         {.code = 0xaa, .group = 1, .size = 2, .mnmx = "res 5,D"},
         {.code = 0xab, .group = 1, .size = 2, .mnmx = "res 5,E"},
         {.code = 0xac, .group = 1, .size = 2, .mnmx = "res 5,H"},
         {.code = 0xad, .group = 1, .size = 2, .mnmx = "res 5,L"},
         {.code = 0xae, .group = 1, .size = 2, .mnmx = "res 5,(HL)"},
         {.code = 0xaf, .group = 1, .size = 2, .mnmx = "res 5,A"},
         {.code = 0xb0, .group = 1, .size = 2, .mnmx = "res 6,B"},
         {.code = 0xb1, .group = 1, .size = 2, .mnmx = "res 6,C"},
         {.code = 0xb2, .group = 1, .size = 2, .mnmx = "res 6,D"},
         {.code = 0xb3, .group = 1, .size = 2, .mnmx = "res 6,E"},
         {.code = 0xb4, .group = 1, .size = 2, .mnmx = "res 6,H"},
         {.code = 0xb5, .group = 1, .size = 2, .mnmx = "res 6,L"},
         {.code = 0xb6, .group = 1, .size = 2, .mnmx = "res 6,(HL)"},
         {.code = 0xb7, .group = 1, .size = 2, .mnmx = "res 6,A"},
         {.code = 0xb8, .group = 1, .size = 2, .mnmx = "res 7,B"},
         {.code = 0xb9, .group = 1, .size = 2, .mnmx = "res 7,C"},
         {.code = 0xba, .group = 1, .size = 2, .mnmx = "res 7,D"},
         {.code = 0xbb, .group = 1, .size = 2, .mnmx = "res 7,E"},
         {.code = 0xbc, .group = 1, .size = 2, .mnmx = "res 7,H"},
         {.code = 0xbd, .group = 1, .size = 2, .mnmx = "res 7,L"},
         {.code = 0xbe, .group = 1, .size = 2, .mnmx = "res 7,(HL)"},
         {.code = 0xbf, .group = 1, .size = 2, .mnmx = "res 7,A"},
         {.code = 0xc0, .group = 1, .size = 2, .mnmx = "set 0,B"},
         {.code = 0xc1, .group = 1, .size = 2, .mnmx = "set 0,C"},
         {.code = 0xc2, .group = 1, .size = 2, .mnmx = "set 0,D"},
         {.code = 0xc3, .group = 1, .size = 2, .mnmx = "set 0,E"},
         {.code = 0xc4, .group = 1, .size = 2, .mnmx = "set 0,H"},
         {.code = 0xc5, .group = 1, .size = 2, .mnmx = "set 0,L"},
         {.code = 0xc6, .group = 1, .size = 2, .mnmx = "set 0,(HL)"},
         {.code = 0xc7, .group = 1, .size = 2, .mnmx = "set 0,A"},
         {.code = 0xc8, .group = 1, .size = 2, .mnmx = "set 1,B"},
         {.code = 0xc9, .group = 1, .size = 2, .mnmx = "set 1,C"},
         {.code = 0xca, .group = 1, .size = 2, .mnmx = "set 1,D"},
         {.code = 0xcb, .group = 1, .size = 2, .mnmx = "set 1,E"},
         {.code = 0xcc, .group = 1, .size = 2, .mnmx = "set 1,H"},
         {.code = 0xcd, .group = 1, .size = 2, .mnmx = "set 1,L"},
         {.code = 0xce, .group = 1, .size = 2, .mnmx = "set 1,(HL)"},
         {.code = 0xcf, .group = 1, .size = 2, .mnmx = "set 1,A"},
         {.code = 0xd0, .group = 1, .size = 2, .mnmx = "set 2,B"},
         {.code = 0xd1, .group = 1, .size = 2, .mnmx = "set 2,C"},
         {.code = 0xd2, .group = 1, .size = 2, .mnmx = "set 2,D"},
         {.code = 0xd3, .group = 1, .size = 2, .mnmx = "set 2,E"},
         {.code = 0xd4, .group = 1, .size = 2, .mnmx = "set 2,H"},
         {.code = 0xd5, .group = 1, .size = 2, .mnmx = "set 2,L"},
         {.code = 0xd6, .group = 1, .size = 2, .mnmx = "set 2,(HL)"},
         {.code = 0xd7, .group = 1, .size = 2, .mnmx = "set 2,A"},
         {.code = 0xd8, .group = 1, .size = 2, .mnmx = "set 3,B"},
         {.code = 0xd9, .group = 1, .size = 2, .mnmx = "set 3,C"},
         {.code = 0xda, .group = 1, .size = 2, .mnmx = "set 3,D"},
         {.code = 0xdb, .group = 1, .size = 2, .mnmx = "set 3,E"},
         {.code = 0xdc, .group = 1, .size = 2, .mnmx = "set 3,H"},
         {.code = 0xdd, .group = 1, .size = 2, .mnmx = "set 3,L"},
         {.code = 0xde, .group = 1, .size = 2, .mnmx = "set 3,(HL)"},
         {.code = 0xdf, .group = 1, .size = 2, .mnmx = "set 3,A"},
         {.code = 0xe0, .group = 1, .size = 2, .mnmx = "set 4,B"},
         {.code = 0xe1, .group = 1, .size = 2, .mnmx = "set 4,C"},
         {.code = 0xe2, .group = 1, .size = 2, .mnmx = "set 4,D"},
         {.code = 0xe3, .group = 1, .size = 2, .mnmx = "set 4,E"},
         {.code = 0xe4, .group = 1, .size = 2, .mnmx = "set 4,H"},
         {.code = 0xe5, .group = 1, .size = 2, .mnmx = "set 4,L"},
         {.code = 0xe6, .group = 1, .size = 2, .mnmx = "set 4,(HL)"},
         {.code = 0xe7, .group = 1, .size = 2, .mnmx = "set 4,A"},
         {.code = 0xe8, .group = 1, .size = 2, .mnmx = "set 5,B"},
         {.code = 0xe9, .group = 1, .size = 2, .mnmx = "set 5,C"},
         {.code = 0xea, .group = 1, .size = 2, .mnmx = "set 5,D"},
         {.code = 0xeb, .group = 1, .size = 2, .mnmx = "set 5,E"},
         {.code = 0xec, .group = 1, .size = 2, .mnmx = "set 5,H"},
         {.code = 0xed, .group = 1, .size = 2, .mnmx = "set 5,L"},
         {.code = 0xee, .group = 1, .size = 2, .mnmx = "set 5,(HL)"},
         {.code = 0xef, .group = 1, .size = 2, .mnmx = "set 5,A"},
         {.code = 0xf0, .group = 1, .size = 2, .mnmx = "set 6,B"},
         {.code = 0xf1, .group = 1, .size = 2, .mnmx = "set 6,C"},
         {.code = 0xf2, .group = 1, .size = 2, .mnmx = "set 6,D"},
         {.code = 0xf3, .group = 1, .size = 2, .mnmx = "set 6,E"},
         {.code = 0xf4, .group = 1, .size = 2, .mnmx = "set 6,H"},
         {.code = 0xf5, .group = 1, .size = 2, .mnmx = "set 6,L"},
         {.code = 0xf6, .group = 1, .size = 2, .mnmx = "set 6,(HL)"},
         {.code = 0xf7, .group = 1, .size = 2, .mnmx = "set 6,A"},
         {.code = 0xf8, .group = 1, .size = 2, .mnmx = "set 7,B"},
         {.code = 0xf9, .group = 1, .size = 2, .mnmx = "set 7,C"},
         {.code = 0xfa, .group = 1, .size = 2, .mnmx = "set 7,D"},
         {.code = 0xfb, .group = 1, .size = 2, .mnmx = "set 7,E"},
         {.code = 0xfc, .group = 1, .size = 2, .mnmx = "set 7,H"},
         {.code = 0xfd, .group = 1, .size = 2, .mnmx = "set 7,L"},
         {.code = 0xfe, .group = 1, .size = 2, .mnmx = "set 7,(HL)"},
         {.code = 0xff, .group = 1, .size = 2, .mnmx = "set 7,A"},
         {.code = 0x00, .group = 0, .size = 0, .mnmx = "unknown"}, // last record mark for look up routine
     };
_opCodes_t opcode_DD[] =
     {   
         {.code = 0x09, .group = 2, .size = 2, .mnmx = "add IX,BC"},
         {.code = 0x19, .group = 2, .size = 2, .mnmx = "add IX,DE"},
         {.code = 0x21, .group = 2, .size = 4, .mnmx = "ld IX,%W"},
         {.code = 0x22, .group = 2, .size = 4, .mnmx = "ld (%W),IX"},
         {.code = 0x23, .group = 2, .size = 2, .mnmx = "inc IX"},
         {.code = 0x29, .group = 2, .size = 2, .mnmx = "add IX,IX"},
         {.code = 0x2a, .group = 2, .size = 4, .mnmx = "ld IX,(%W)"},
         {.code = 0x2b, .group = 2, .size = 2, .mnmx = "dec IX"},
         {.code = 0x34, .group = 2, .size = 3, .mnmx = "inc (IX+%B)"},
         {.code = 0x35, .group = 2, .size = 3, .mnmx = "dec (IX+%B)"},
         {.code = 0x36, .group = 2, .size = 4, .mnmx = "ld (IX+%B),%B"},
         {.code = 0x39, .group = 2, .size = 2, .mnmx = "add IX,SP"},
         {.code = 0x46, .group = 2, .size = 3, .mnmx = "ld B,(IX+%B)"},
         {.code = 0x4e, .group = 2, .size = 3, .mnmx = "ld C,(IX+%B)"},
         {.code = 0x56, .group = 2, .size = 3, .mnmx = "ld D,(IX+%B)"},
         {.code = 0x5e, .group = 2, .size = 3, .mnmx = "ld E,(IX+%B)"},
         {.code = 0x66, .group = 2, .size = 3, .mnmx = "ld H,(IX+%B)"},
         {.code = 0x6e, .group = 2, .size = 3, .mnmx = "ld L,(IX+%B)"},
         {.code = 0x70, .group = 2, .size = 3, .mnmx = "ld (IX+%B),B"},
         {.code = 0x71, .group = 2, .size = 3, .mnmx = "ld (IX+%B),C"},
         {.code = 0x72, .group = 2, .size = 3, .mnmx = "ld (IX+%B),D"},
         {.code = 0x73, .group = 2, .size = 3, .mnmx = "ld (IX+%B),E"},
         {.code = 0x74, .group = 2, .size = 3, .mnmx = "ld (IX+%B),H"},
         {.code = 0x75, .group = 2, .size = 3, .mnmx = "ld (IX+%B),L"},
         {.code = 0x77, .group = 2, .size = 3, .mnmx = "ld (IX+%B),A"},
         {.code = 0x7e, .group = 2, .size = 3, .mnmx = "ld A,(IX+%B)"},
         {.code = 0x86, .group = 2, .size = 3, .mnmx = "add A,(IX+%B)"},
         {.code = 0x8e, .group = 2, .size = 3, .mnmx = "adc A,(IX+%B)"},
         {.code = 0x96, .group = 2, .size = 3, .mnmx = "sub (IX+%B)"},
         {.code = 0x9e, .group = 2, .size = 3, .mnmx = "sbc A,(IX+%B)"},
         {.code = 0xa6, .group = 2, .size = 3, .mnmx = "and (IX+%B)"},
         {.code = 0xae, .group = 2, .size = 3, .mnmx = "xor (IX+%B)"},
         {.code = 0xb6, .group = 2, .size = 3, .mnmx = "or (IX+%B)"},
         {.code = 0xbe, .group = 2, .size = 3, .mnmx = "cp (IX+%B)"},
         {.code = 0xe1, .group = 2, .size = 2, .mnmx = "pop IX"},
         {.code = 0xe3, .group = 2, .size = 2, .mnmx = "ex (SP),IX"},
         {.code = 0xe5, .group = 2, .size = 2, .mnmx = "push IX"},
         {.code = 0xe9, .group = 2, .size = 2, .mnmx = "jp (IX)"},
         {.code = 0xf9, .group = 2, .size = 2, .mnmx = "ld SP,IX"},
         {.code = 0x00, .group = 0, .size = 0, .mnmx = "unknown"}, // last record mark for look up routine         
     };
_opCodes_t opcode_DDCB[] =     
     {   /// Group DDCB,
         {.code = 0x06, .group = 3, .size = 4, .mnmx = "rlc (IX+%B)"},
         {.code = 0x0e, .group = 3, .size = 4, .mnmx = "rrc (IX+%B)"},
         {.code = 0x16, .group = 3, .size = 4, .mnmx = "rl (IX+%B)"},
         {.code = 0x1e, .group = 3, .size = 4, .mnmx = "rr (IX+%B)"},
         {.code = 0x26, .group = 3, .size = 4, .mnmx = "sla (IX+%B)"},
         {.code = 0x2e, .group = 3, .size = 4, .mnmx = "sra (IX+%B)"},
         {.code = 0x3e, .group = 3, .size = 4, .mnmx = "srl (IX+%B)"},
         {.code = 0x46, .group = 3, .size = 4, .mnmx = "bit 0,(IX+%B)"},
         {.code = 0x4e, .group = 3, .size = 4, .mnmx = "bit 1,(IX+%B)"},
         {.code = 0x56, .group = 3, .size = 4, .mnmx = "bit 2,(IX+%B)"},
         {.code = 0x5e, .group = 3, .size = 4, .mnmx = "bit 3,(IX+%B)"},
         {.code = 0x67, .group = 3, .size = 4, .mnmx = "bit 4,(IX+%B)"},
         {.code = 0x6e, .group = 3, .size = 4, .mnmx = "bit 5,(IX+%B)"},
         {.code = 0x76, .group = 3, .size = 4, .mnmx = "bit 6,(IX+%B)"},
         {.code = 0x7e, .group = 3, .size = 4, .mnmx = "bit 7,(IX+%B)"},
         {.code = 0x86, .group = 3, .size = 4, .mnmx = "res 0,(IX+%B)"},
         {.code = 0x8e, .group = 3, .size = 4, .mnmx = "res 1,(IX+%B)"},
         {.code = 0x96, .group = 3, .size = 4, .mnmx = "res 2,(IX+%B)"},
         {.code = 0x9e, .group = 3, .size = 4, .mnmx = "res 3,(IX+%B)"},
         {.code = 0xa6, .group = 3, .size = 4, .mnmx = "res 4,(IX+%B)"},
         {.code = 0xae, .group = 3, .size = 4, .mnmx = "res 5,(IX+%B)"},
         {.code = 0xb6, .group = 3, .size = 4, .mnmx = "res 6,(IX+%B)"},
         {.code = 0xbe, .group = 3, .size = 4, .mnmx = "res 7,(IX+%B)"},
         {.code = 0xc6, .group = 3, .size = 4, .mnmx = "set 0,(IX+%B)"},
         {.code = 0xce, .group = 3, .size = 4, .mnmx = "set 1,(IX+%B)"},
         {.code = 0xd6, .group = 3, .size = 4, .mnmx = "set 2,(IX+%B)"},
         {.code = 0xde, .group = 3, .size = 4, .mnmx = "set 3,(IX+%B)"},
         {.code = 0xe6, .group = 3, .size = 4, .mnmx = "set 4,(IX+%B)"},
         {.code = 0xee, .group = 3, .size = 4, .mnmx = "set 5,(IX+%B)"},
         {.code = 0xf6, .group = 3, .size = 4, .mnmx = "set 6,(IX+%B)"},
         {.code = 0xfe, .group = 3, .size = 4, .mnmx = "set 7,(IX+%B)"},
         {.code = 0x00, .group = 0, .size = 0, .mnmx = "unknown"}, // last record mark for look up routine         
     };
_opCodes_t opcode_ED[] =      
     {   ///    OPGR_ED,
         {.code = 0x40, .group = 4, .size = 2, .mnmx = "in B,(C)"},
         {.code = 0x41, .group = 4, .size = 2, .mnmx = "out (C),B"},
         {.code = 0x42, .group = 4, .size = 2, .mnmx = "sbc HL,BC"},
         {.code = 0x43, .group = 4, .size = 4, .mnmx = "ld (%W),BC"},
         {.code = 0x44, .group = 4, .size = 2, .mnmx = "neg"},
         {.code = 0x45, .group = 4, .size = 2, .mnmx = "retn"},
         {.code = 0x46, .group = 4, .size = 2, .mnmx = "im 0"},
         {.code = 0x47, .group = 4, .size = 2, .mnmx = "ld I,A"},
         {.code = 0x48, .group = 4, .size = 2, .mnmx = "in C,(C)"},
         {.code = 0x49, .group = 4, .size = 2, .mnmx = "out (C),C"},
         {.code = 0x4a, .group = 4, .size = 2, .mnmx = "adc HL,BC"},
         {.code = 0x4b, .group = 4, .size = 4, .mnmx = "ld BC,%W"},
         {.code = 0x4d, .group = 4, .size = 2, .mnmx = "reti"},
         {.code = 0x4f, .group = 4, .size = 2, .mnmx = "ld R,A"},
         {.code = 0x50, .group = 4, .size = 2, .mnmx = "in D,(C)"},
         {.code = 0x51, .group = 4, .size = 2, .mnmx = "out (C),D"},
         {.code = 0x52, .group = 4, .size = 2, .mnmx = "sbc HL,DE"},
         {.code = 0x53, .group = 4, .size = 4, .mnmx = "ld (%W),DE"},
         {.code = 0x56, .group = 4, .size = 2, .mnmx = "im 1"},
         {.code = 0x57, .group = 4, .size = 2, .mnmx = "ld A,I"},
         {.code = 0x58, .group = 4, .size = 2, .mnmx = "in E,(C)"},
         {.code = 0x59, .group = 4, .size = 2, .mnmx = "out (C),E"},
         {.code = 0x5a, .group = 4, .size = 2, .mnmx = "adc HL,DE"},
         {.code = 0x5b, .group = 4, .size = 4, .mnmx = "ld DE,(%W)"},
         {.code = 0x5e, .group = 4, .size = 2, .mnmx = "im 2"},
         {.code = 0x5f, .group = 4, .size = 2, .mnmx = "ld A,R"},
         {.code = 0x60, .group = 4, .size = 2, .mnmx = "in H"},
         {.code = 0x61, .group = 4, .size = 2, .mnmx = "out (C),H"},
         {.code = 0x62, .group = 4, .size = 2, .mnmx = "sbc HL,HL"},
         {.code = 0x63, .group = 4, .size = 4, .mnmx = "ld DE,(%W)"},
         {.code = 0x67, .group = 4, .size = 2, .mnmx = "rrd"},
         {.code = 0x68, .group = 4, .size = 2, .mnmx = "in L,(C)"},
         {.code = 0x69, .group = 4, .size = 2, .mnmx = "out (C),L"},
         {.code = 0x6a, .group = 4, .size = 2, .mnmx = "adc HL,HL"},
         {.code = 0x6b, .group = 4, .size = 4, .mnmx = "ld HL,(%W)"},
         {.code = 0x6f, .group = 4, .size = 2, .mnmx = "rld"},
         {.code = 0x70, .group = 4, .size = 2, .mnmx = "in F,(C)"},
         {.code = 0x72, .group = 4, .size = 2, .mnmx = "sbc HL,SP"},
         {.code = 0x73, .group = 4, .size = 4, .mnmx = "ld (%W),SP"},
         {.code = 0x78, .group = 4, .size = 2, .mnmx = "in A,(C)"},
         {.code = 0x79, .group = 4, .size = 2, .mnmx = "out (C),A"},
         {.code = 0x7a, .group = 4, .size = 2, .mnmx = "adc HL,SP"},
         {.code = 0x7b, .group = 4, .size = 4, .mnmx = "ld SP,(%W)"},
         {.code = 0xa0, .group = 4, .size = 2, .mnmx = "ldi"},
         {.code = 0xa1, .group = 4, .size = 2, .mnmx = "cpi"},
         {.code = 0xa2, .group = 4, .size = 2, .mnmx = "ini"},
         {.code = 0xa3, .group = 4, .size = 2, .mnmx = "outi"},
         {.code = 0xa8, .group = 4, .size = 2, .mnmx = "ldd"},
         {.code = 0xa9, .group = 4, .size = 2, .mnmx = "cpd"},
         {.code = 0xaa, .group = 4, .size = 2, .mnmx = "ind"},
         {.code = 0xab, .group = 4, .size = 2, .mnmx = "outd"},
         {.code = 0xb0, .group = 4, .size = 2, .mnmx = "ldir"},
         {.code = 0xb1, .group = 4, .size = 2, .mnmx = "cpir"},
         {.code = 0xb2, .group = 4, .size = 2, .mnmx = "inir"},
         {.code = 0xb3, .group = 4, .size = 2, .mnmx = "otir"},
         {.code = 0xb8, .group = 4, .size = 2, .mnmx = "lddr"},
         {.code = 0xb9, .group = 4, .size = 2, .mnmx = "cpdr"},
         {.code = 0xba, .group = 4, .size = 2, .mnmx = "indr"},
         {.code = 0xbb, .group = 4, .size = 2, .mnmx = "otdr"},
         {.code = 0x00, .group = 0, .size = 0, .mnmx = "unknown"}, // last record mark for look up routine         
     };
_opCodes_t opcode_FD[] =      
     {   /// Group FD,
         {.code = 0x09, .group = 5, .size = 2, .mnmx = "add IY,BC"},
         {.code = 0x19, .group = 5, .size = 2, .mnmx = "add IY,DE"},
         {.code = 0x21, .group = 5, .size = 4, .mnmx = "ld IY,%W"},
         {.code = 0x22, .group = 5, .size = 4, .mnmx = "ld (%W),IY"},
         {.code = 0x23, .group = 5, .size = 2, .mnmx = "inc IY"},
         {.code = 0x29, .group = 5, .size = 2, .mnmx = "add IY,IY"},
         {.code = 0x2a, .group = 5, .size = 4, .mnmx = "ld IY,(%W)"},
         {.code = 0x2b, .group = 5, .size = 2, .mnmx = "dec IY"},
         {.code = 0x34, .group = 5, .size = 3, .mnmx = "inc (IY+%B)"},
         {.code = 0x35, .group = 5, .size = 3, .mnmx = "dec (IY+%B)"},
         {.code = 0x36, .group = 5, .size = 4, .mnmx = "ld (IY+%B),%B"},
         {.code = 0x39, .group = 5, .size = 2, .mnmx = "add IY,SP"},
         {.code = 0x46, .group = 5, .size = 3, .mnmx = "ld B,(IY+%B)"},
         {.code = 0x4e, .group = 5, .size = 3, .mnmx = "ld C,(IY+%B)"},
         {.code = 0x56, .group = 5, .size = 3, .mnmx = "ld D,(IY+%B)"},
         {.code = 0x5e, .group = 5, .size = 3, .mnmx = "ld E,(IY+%B)"},
         {.code = 0x66, .group = 5, .size = 3, .mnmx = "ld H,(IY+%B)"},
         {.code = 0x6e, .group = 5, .size = 3, .mnmx = "ld L,(IY+%B)"},
         {.code = 0x70, .group = 5, .size = 3, .mnmx = "ld (IY+%B),B"},
         {.code = 0x71, .group = 5, .size = 3, .mnmx = "ld (IY+%B),C"},
         {.code = 0x72, .group = 5, .size = 3, .mnmx = "ld (IY+%B),D"},
         {.code = 0x73, .group = 5, .size = 3, .mnmx = "ld (IY+%B),E"},
         {.code = 0x74, .group = 5, .size = 3, .mnmx = "ld (IY+%B),H"},
         {.code = 0x75, .group = 5, .size = 3, .mnmx = "ld (IY+%B),L"},
         {.code = 0x77, .group = 5, .size = 3, .mnmx = "ld (IY+%B),A"},
         {.code = 0x7e, .group = 5, .size = 3, .mnmx = "ld A,(IY+%B)"},
         {.code = 0x86, .group = 5, .size = 3, .mnmx = "add A,(IY+%B)"},
         {.code = 0x8e, .group = 5, .size = 3, .mnmx = "adc A,(IY+%B)"},
         {.code = 0x96, .group = 5, .size = 3, .mnmx = "sub (IY+%B)"},
         {.code = 0x9e, .group = 5, .size = 3, .mnmx = "sbc A,(IY+%B)"},
         {.code = 0xa6, .group = 5, .size = 3, .mnmx = "and (IY+%B)"},
         {.code = 0xae, .group = 5, .size = 3, .mnmx = "xor (IY+%B)"},
         {.code = 0xb6, .group = 5, .size = 3, .mnmx = "or (IY+%B)"},
         {.code = 0xbe, .group = 5, .size = 3, .mnmx = "cp (IY+%B)"},
         {.code = 0xe1, .group = 5, .size = 2, .mnmx = "pop IY"},
         {.code = 0xe3, .group = 5, .size = 2, .mnmx = "ex (SP),IY"},
         {.code = 0xe5, .group = 5, .size = 2, .mnmx = "push IY"},
         {.code = 0xe9, .group = 5, .size = 2, .mnmx = "jp (IY)"},
         {.code = 0xf9, .group = 5, .size = 2, .mnmx = "ld SP,IY"},
         {.code = 0x00, .group = 0, .size = 0, .mnmx = "unknown"}, // last record mark for look up routine         
     };
_opCodes_t opcode_FDCB[] =      
     {   /// Group FDCB
         {.code = 0x06, .group = 6, .size = 4, .mnmx = "rlc (IY+%B)"},
         {.code = 0x0e, .group = 6, .size = 4, .mnmx = "rrc (IY+%B)"},
         {.code = 0x16, .group = 6, .size = 4, .mnmx = "rl (IY+%B)"},
         {.code = 0x1e, .group = 6, .size = 4, .mnmx = "rr (IY+%B)"},
         {.code = 0x26, .group = 6, .size = 4, .mnmx = "sla (IY+%B)"},
         {.code = 0x2e, .group = 6, .size = 4, .mnmx = "sra (IY+%B)"},
         {.code = 0x3e, .group = 6, .size = 4, .mnmx = "srl (IY+%B)"},
         {.code = 0x46, .group = 6, .size = 4, .mnmx = "bit 0,(IY+%B)"},
         {.code = 0x4e, .group = 6, .size = 4, .mnmx = "bit 1,(IY+%B)"},
         {.code = 0x56, .group = 6, .size = 4, .mnmx = "bit 2,(IY+%B)"},
         {.code = 0x5e, .group = 6, .size = 4, .mnmx = "bit 3,(IY+%B)"},
         {.code = 0x67, .group = 6, .size = 4, .mnmx = "bit 4,(IY+%B)"},
         {.code = 0x6e, .group = 6, .size = 4, .mnmx = "bit 5,(IY+%B)"},
         {.code = 0x76, .group = 6, .size = 4, .mnmx = "bit 6,(IY+%B)"},
         {.code = 0x7e, .group = 6, .size = 4, .mnmx = "bit 7,(IY+%B)"},
         {.code = 0x86, .group = 6, .size = 4, .mnmx = "res 0,(IY+%B)"},
         {.code = 0x8e, .group = 6, .size = 4, .mnmx = "res 1,(IY+%B)"},
         {.code = 0x96, .group = 6, .size = 4, .mnmx = "res 2,(IY+%B)"},
         {.code = 0x9e, .group = 6, .size = 4, .mnmx = "res 3,(IY+%B)"},
         {.code = 0xa6, .group = 6, .size = 4, .mnmx = "res 4,(IY+%B)"},
         {.code = 0xae, .group = 6, .size = 4, .mnmx = "res 5,(IY+%B)"},
         {.code = 0xb6, .group = 6, .size = 4, .mnmx = "res 6,(IY+%B)"},
         {.code = 0xbe, .group = 6, .size = 4, .mnmx = "res 7,(IY+%B)"},
         {.code = 0xc6, .group = 6, .size = 4, .mnmx = "set 0,(IY+%B)"},
         {.code = 0xce, .group = 6, .size = 4, .mnmx = "set 1,(IY+%B)"},
         {.code = 0xd6, .group = 6, .size = 4, .mnmx = "set 2,(IY+%B)"},
         {.code = 0xde, .group = 6, .size = 4, .mnmx = "set 3,(IY+%B)"},
         {.code = 0xe6, .group = 6, .size = 4, .mnmx = "set 4,(IY+%B)"},
         {.code = 0xee, .group = 6, .size = 4, .mnmx = "set 5,(IY+%B)"},
         {.code = 0xf6, .group = 6, .size = 4, .mnmx = "set 6,(IY+%B)"},
         {.code = 0xfe, .group = 6, .size = 4, .mnmx = "set 7,(IY+%B)"},
         {.code = 0x00, .group = 0, .size = 0, .mnmx = "unknown"}, // last record mark for look up routine         
     };


_opCodes_t *z80instr[7] =
{
    opcode_basic,
    opcode_CB,
    opcode_DD,
    opcode_DDCB,
    opcode_ED,
    opcode_FD,
    opcode_FDCB,
};